### ISSUE TITLE
violates AGPL v3 § 5 because of copied/adapted code from TechnoVisionDev/TechnoBot

### ISSUE THREAD

**Issue by xf8b** [KingRealzYT/CBot#2]
See:
[Definition of "modify" in the Affero General Public License, version 3](https://github.com/TechnoVisionDev/TechnoBot/blob/master/COPYING#L72-L75)
[AGPL v3 § 5](https://github.com/TechnoVisionDev/TechnoBot/blob/master/COPYING#L196-L231)

**Comment by KingRealzYT** [comment]
uhhhh no comment

**Comment by xf8b** [comment]
violating copyright law goes brrrr

**Comment by KingRealzYT** [comment]
hey im not anymore.
